AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false