name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '*.*.*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1-alpine
    steps:
      - name: Install dependencies
        run: apk add --no-cache build-base git libffi-dev yaml-dev tzdata

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Run RSpec
        run: bundle exec rspec

